-- 01) Find the total revenue generated by each customer (Window Function)

SELECT 
    c.Name,
    SUM(p.Price * o.Quantity) AS TotalRevenue,
    RANK() OVER (ORDER BY SUM(p.Price * o.Quantity) DESC) AS RevenueRank
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
JOIN Products p ON o.ProductID = p.ProductID
GROUP BY c.Name;
