-- 01) Total Revenue Generated by Each Customer

SELECT 
    c.Name,
    SUM(p.Price * o.Quantity) AS Total_Revenue
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
JOIN Products p ON o.ProductID = p.ProductID
GROUP BY c.Name;

